server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, nexura
      routes:
        - id: oj_route
          uri: http://127.0.0.0:18121/api
          predicates:
            - Path=/nextoj/**
        - id: bi_route
          uri: http://127.0.0.0:18123/api
          predicates:
            - Path=/nextbi/**
        - id: brainu_route
          uri: http://127.0.0.0:18221/api
          predicates:
            - Path=/brainu/**

dubbo:
  application:
    name: next-api-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://43.143.20.63:8848
  provider:
    prefer-serialization: fastjson2