server:
  port: 80
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, nexura
      routes:
        - id: api_route
          uri: http://127.0.0.1:9178
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: next-api-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://120.46.207.211:8848